"""activity external_id + constraints

Revision ID: 01e6af724c5c
Revises: 07950bcf718c
Create Date: 2026-01-23 18:08:05.495144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e6af724c5c'
down_revision = '07950bcf718c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=120), nullable=False))
        batch_op.create_index(batch_op.f('ix_activities_external_id'), ['external_id'], unique=True)

    with op.batch_alter_table('activity_completions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_session_activity', ['daily_session_id', 'activity_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_completions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_session_activity', type_='unique')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_external_id'))
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
