"""empty message

Revision ID: 07950bcf718c
Revises: 0763d677d453
Create Date: 2026-01-19 18:57:50.600246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07950bcf718c'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('url_music', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('day_start_time', sa.Time(), nullable=False),
    sa.Column('night_start_time', sa.Time(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('welcome_email_sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('activity_type', sa.Enum('day', 'night', 'both', name='activitytype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['activity_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('ix_activities_category', ['category_id'], unique=False)

    op.create_table('daily_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('session_type', sa.Enum('day', 'night', name='sessiontype'), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_date', 'session_type', name='uq_session_user_date_type')
    )
    with op.batch_alter_table('daily_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_daily_sessions_user_date', ['user_id', 'session_date'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Enum('small', 'medium', 'large', name='goalsize'), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('current_value >= 0', name='ck_goal_current_nonneg'),
    sa.CheckConstraint('target_value >= 0', name='ck_goal_target_nonneg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index('ix_goals_user', ['user_id'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.Enum('welcome', 'goal_daily', 'activity_daily', 'inactive_nudge', 'day_session', 'night_session', name='remindertype'), nullable=False),
    sa.Column('mode', sa.Enum('fixed', 'inactivity', name='remindermode'), nullable=False),
    sa.Column('local_time', sa.Time(), nullable=True),
    sa.Column('inactive_after_minutes', sa.Integer(), nullable=True),
    sa.Column('days_of_week', sa.String(length=40), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index('ix_reminders_user', ['user_id'], unique=False)
        batch_op.create_index('ix_reminders_user_type_active', ['user_id', 'reminder_type', 'is_active'], unique=False)

    op.create_table('activity_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_session_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('points_awarded >= 0', name='ck_activity_points_nonneg'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['daily_session_id'], ['daily_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_completions', schema=None) as batch_op:
        batch_op.create_index('ix_activity_completions_activity', ['activity_id'], unique=False)
        batch_op.create_index('ix_activity_completions_session', ['daily_session_id'], unique=False)

    op.create_table('daily_session_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_session_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'done', 'skipped', name='sessiongoalstatus'), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_session_id'], ['daily_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_session_id', 'goal_id', name='uq_session_goal')
    )
    with op.batch_alter_table('daily_session_goals', schema=None) as batch_op:
        batch_op.create_index('ix_session_goals_goal', ['goal_id'], unique=False)
        batch_op.create_index('ix_session_goals_session', ['daily_session_id'], unique=False)

    op.create_table('emotion_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_session_id', sa.Integer(), nullable=False),
    sa.Column('emotion_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_session_id'], ['daily_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emotion_checkins', schema=None) as batch_op:
        batch_op.create_index('ix_emotion_checkins_emotion', ['emotion_id'], unique=False)
        batch_op.create_index('ix_emotion_checkins_session', ['daily_session_id'], unique=False)

    op.create_table('goal_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('daily_session_id', sa.Integer(), nullable=True),
    sa.Column('delta_value', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_session_id'], ['daily_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal_progress', schema=None) as batch_op:
        batch_op.create_index('ix_goal_progress_goal', ['goal_id'], unique=False)
        batch_op.create_index('ix_goal_progress_session', ['daily_session_id'], unique=False)

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('goal_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_goal_progress_session')
        batch_op.drop_index('ix_goal_progress_goal')

    op.drop_table('goal_progress')
    with op.batch_alter_table('emotion_checkins', schema=None) as batch_op:
        batch_op.drop_index('ix_emotion_checkins_session')
        batch_op.drop_index('ix_emotion_checkins_emotion')

    op.drop_table('emotion_checkins')
    with op.batch_alter_table('daily_session_goals', schema=None) as batch_op:
        batch_op.drop_index('ix_session_goals_session')
        batch_op.drop_index('ix_session_goals_goal')

    op.drop_table('daily_session_goals')
    with op.batch_alter_table('activity_completions', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_completions_session')
        batch_op.drop_index('ix_activity_completions_activity')

    op.drop_table('activity_completions')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index('ix_reminders_user_type_active')
        batch_op.drop_index('ix_reminders_user')

    op.drop_table('reminders')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index('ix_goals_user')

    op.drop_table('goals')
    with op.batch_alter_table('daily_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_sessions_user_date')

    op.drop_table('daily_sessions')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('ix_activities_category')

    op.drop_table('activities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('emotions')
    op.drop_table('activity_categories')
    # ### end Alembic commands ###
