"""empty message

Revision ID: 60749c12da0e
Revises: 01e6af724c5c
Create Date: 2026-01-24 22:27:57.304021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60749c12da0e'
down_revision = '01e6af724c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emotion_checkins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intensity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emotion_checkins', schema=None) as batch_op:
        batch_op.drop_column('intensity')

    # ### end Alembic commands ###
